{% set version = "1.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-distutils
  version: {{ version }}

source:
  url: https://github.com/Albluca/distutils/archive/cd82bcac0aa919261813a542f2e4a4939eeecace.zip
  sha256: 296464ab1a77a99761a80e46a30053ccbca4e75c42e127803ae54a6f7ba1408a

build:
  number: 1007
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-rcpparmadillo >=0.7.960
    - libblas
    - liblapack
  run:
    - r-base
    - r-rcpp >=0.12.12
    - r-rcpparmadillo >=0.7.960

test:
  commands:
    - $R -e "library('distutils')"           # [not win]
    - "\"%R%\" -e \"library('distutils')\""  # [win]

about:
  home: https://github.com/Albluca/distutils
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A fast implementation of distance computation with RCpp'
  description: |
    A collection of C++ functions for fast computation of distances and elastic energies

extra:
  recipe-maintainers:
    - conda-forge/r
    - lucapinello
